org: carterh
app: sleepnumber
service: lambdas

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  lambdaHashingVersion: '20201221'
  environment:
    API_KEY: ${env:API_KEY}

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

functions:
  setSleepNumber:
    handler: src/index.setSleepNumber
    events:
      - http:
          path: setSleepNumber
          method: post